### ISSUE TITLE
Implement Individual Service Calls

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#4]
- [ ] Add Drones
- [ ] Upload Mission
- [ ] StartMission(ID)
- [ ] PauseMission(ID)
- [ ] ResumeMission(ID)
- [ ] LandDrone(ID)
- [ ] FlyHome(ID)

See [API document](https://docs.google.com/document/d/1g3dKYSgtFYrp6Fd4SA6JV8K353C8m3OqXH_cyjhj9-0/edit) for more details.

**Comment by varunsaran** [comment]
Added control_drone service, a generic service that takes in drone ID and a string, and accordingly calls: (the string defines which method to call)
 -    land_drone
-   start_mission
-   pause_mission
-   resume_mission
-  fly_home

We decided to have this generic service because we think it might be cleaner than defining a whole bunch of services that just make 1 function call. These methods don't need any preprocessing, and the only input is the drone ID, so it should be fine.

For things like upload_mission, which need inputs like a list of waypoints, they can have their own service.

**Comment by DragonKyro** [comment]
Karthik, Varun, and Kyle completed the following:

State dictionaries:
- sensors global dictionary
- drone_names dictionary
- sensor_names dictionary

Service handlers:
- register_sensor

Skeleton code for shutdown_drones

**Comment by varunsaran** [comment]
next_id now starts at 1, not 0. 0 is reserved for services to ask for info about ALL drones + services, not a particular one

implemented all_available_drones
implemented query_topics

other minor edits

TODO:
make sensor base class
add list of sensor ids to the parent drone instance when registering a sensor.
